# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:latest # Menggunakan versi PostgreSQL terbaru
    container_name: portal_berita_db_new # Nama container baru agar tidak konflik
    environment:
      POSTGRES_DB: portal_berita_new # Nama database baru
      POSTGRES_USER: user_baru # Username baru
      POSTGRES_PASSWORD: mysecretpassword # Password baru yang umum untuk debugging
    volumes:
      - db_data_new:/var/lib/postgresql/data # Volume data baru
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  db_data_new: # Definisi volume baru